### ISSUE TITLE
Blog post previews in Safari are a bit hard to click

### ISSUE THREAD

**Issue by tommyschaefer** [KittyCAD/support#18]
**Describe the bug**

Hi there! I was on the blog today, and noticed that it's a bit hard to click through to posts on my version of Safari. Because the animated horizontal lines are overlaid, only the very top and very bottom of the preview card are clickable for me.

While writing this up, I checkout out the blog on Firefox, and realized that maybe the lines are actually supposed to be behind the preview card, which makes the whole card clickable.

Apologies if this is just on my (probably out of date) version of Safari!

**Screenshots**

On my version of Safari:

https://github.com/KittyCAD/support/assets/784253/fb3e1068-4c79-42b3-ba41-8d2bb1375551

On my version of Firefox:

<img width="1063" alt="image" src="https://github.com/KittyCAD/support/assets/784253/fcd22d4f-8c0e-4f49-b499-27b2e49cee2e">

**Desktop (please complete the following information):**
 - OS: macOS 12.6.7
 - Browser: Safari Version 16.5.1 (17615.2.9.11.7, 17615)

**Comment by franknoirot** [comment]
This was a great issue, thanks @tommyschaefer sorry I missed it! We've redesigned the site recently and now the blog links don't have that "scanline" effect, so the bug that you seem to have found with Safari is no longer an issue (incidentally, I think this was an oversight on my part not remembering that Safari uses Z-axis translate to stack items like this instead of z-index like everyone else). Here's what clicking them on Safari works now:


Uploading Screen Recording 2024-01-07 at 3.48.59 PM.mov…
